elasticsearch:
    image: elasticsearch:1.7
logstash:
    image: logstash:1.5
    volumes:
        - ./logstash.conf:/etc/logstash.conf
    ports:
        - "6000:6000"
    links:
        - elasticsearch
    command: logstash -f /etc/logstash.conf
kibana:
    image: kibana:4.1
    ports:
        - "5601:5601"
    links:
        - elasticsearch
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
